sonar.projectKey=frederico-mello_receitas-desafio-vegano
sonar.organization=frederico-mello
sonar.python.version=3
sonar.sources=.
sonar.exclusions=**/*.md
sonar.python.coverage.reportPaths=coverage.xml
