sonar.projectKey=frederico-mello_receitas-desafio-vegano
sonar.organization=frederico-mello
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=src/
sonar.tests=tests/
sonar.exclusions=tests/**
sonar.python.version=3.11
