"""initial schema

Revision ID: 95a0993676bb
Revises: 
Create Date: 2026-07-25 07:48:04.805945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

_CURRENT_TIMESTAMP_SQL = '(CURRENT_TIMESTAMP)'


# revision identifiers, used by Alembic.
revision: str = '95a0993676bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('recipe_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text(_CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('content_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('original_input', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text(_CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_person_id'), 'inventory_items', ['person_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('preparation_steps', sa.JSON(), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('previous_version_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(_CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text(_CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['recipe_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_index(op.f('ix_inventory_items_person_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('recipe_sources')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
